---
title: "Processing"
author: "Team #3"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r warnign=FALSE}
setwd("~/projects/thesis-code")
options(max.print=1000000)
library(readr)
library(stringr)
library(ggplot2)
library(dplyr)
library(corrplot)
library(gridExtra)
library(data.table)
library(rattle)
library(fastDummies)
library(stargazer)
library(glmnet)
library(caret)
library(ISLR) #contains Hitters dataset
library(rpart) #for fitting decision trees
library(rpart.plot) #for plotting decision trees
```

```{r}
colnames(df)
```

# Choose variables

```{r}
pcatdf <- select(df, price_in_usd, Close, first_transaction, date, winner_flow, winner_total_sold, winner_total_bought, prev_price, trait_Type, trait_Pants, trait_Pants_Color, trait_Shoes, trait_Shoes_Color, trait_Shirt, trait_Shirt_Color, trait_Hair_Style, trait_Hair_Color, trait_Glasses, trait_Glasses_Color, trait_Overshirt, trait_Overshirt_Color, trait_Beard, trait_Beard_Color, trait_Hat, trait_Hat_Color, trait_Jersey_Number, trait_Necklace, trait_Earring)
pcatdf[is.na(pcatdf)] <- 0

rdf <- pcatdf

colnms = colnames(rdf)
c = 0
for (i in colnms) {
  if (c > 7) {
    print(i)
    rdf <- dummy_cols(rdf, select_columns = i, remove_selected_columns=TRUE, remove_first_dummy=FALSE)
  }
  c = c + 1
}

rdf$prev_price = log(rdf$prev_price)
rdf$prev_price[which(!is.finite(rdf$prev_price))] <- 0

rdf = rdf[,!(names(rdf) %in% c(
  "trait_Shoes_Color_0",
  "trait_Pants_Color_0",
  "trait_Pants_Color_19",
  "trait_Shirt_Color_0",
  "trait_Overshirt_Color_0",
  "trait_Hat_Color_0",
  "trait_Hair_Color_0",
  "trait_Beard_Color_0", # no beard without color
  "trait_Glasses_Color_0",
  "trait_Jersey_Number_0", # no Jersey stuff without number

  "trait_Necklace_0",
  "trait_Earring_0",

  "trait_Shirt_18", # Don't know why, but hoodie only exist without oveshirt

  "trait_Hat_Color_1",
  "trait_Beard_Color_1",
  "trait_Overshirt_Color_1",
  "trait_Glasses_Color_1",
  "trait_Hair_Color_1",
  "trait_Shirt_Color_1",
  "trait_Shoes_Color_1",

  "trait_Type_1",
  "trait_Shoes_1",
  "trait_Pants_1",
  "trait_Shirt_1",
  "trait_Overshirt_0",
  "trait_Hat_0",
  "trait_Hair_Style_1",
  "trait_Beard_0",
  "trait_Glasses_0",
  "trait_Jersey_Number_1"
  ))]
```

# Date manipulation

## Month

```{r}
rdf$month<- strftime(rdf$date,"%m")
rdf <- dummy_cols(rdf, select_columns = "month", remove_selected_columns=TRUE, remove_first_dummy=TRUE)
rdf = rdf[,!(names(rdf) %in% c("date"))]
#colnames(rdf)
```

# First regression

```{r}
reg1 = lm(log(price_in_usd) ~ .-first_transaction, data = rdf)
```

## Elastic Net

```{r}
set.seed(42) # Set seed for reproducibility

n <- dim(rdf)[1]    # Number of observations
p <- dim(rdf)[2]     # Number of predictors included in model

xdf <- select(rdf, -c(price_in_usd,first_transaction))
x <- data.matrix(xdf)
y <- log(rdf$price_in_usd)

# Split data into train (2/3) and test (1/3) sets
train_rows <- sample(1:n, .66*n)
x.train <- x[train_rows, ]
x.test <- x[-train_rows, ]

y.train <- y[train_rows]
y.test <- y[-train_rows]

list.of.fits <- list()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)

  list.of.fits[[fit.name]] <-
    cv.glmnet(x.train, y.train, type.measure="mse", alpha=i/10,
      family="gaussian")
}

results <- data.frame()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)

  predicted <-
    predict(list.of.fits[[fit.name]],
      s=list.of.fits[[fit.name]]$lambda.1se, newx=x.test)

  mse <- mean((y.test - predicted)^2)

  temp <- data.frame(alpha=i/10, mse=mse, fit.name=fit.name)
  results <- rbind(results, temp)
}

results
```

```{r}
reg1.1 <- cv.glmnet(x, y, type.measure="mse", alpha=1, family="gaussian")
coef(reg1.1)
```

# Date manipulation

```{r}
pcatdf <- select(df, price_in_usd, Close, date, rarityScore, winner_flow, winner_total_sold, winner_total_bought, first_transaction, prev_price)
pcatdf[is.na(pcatdf)] <- 0
rdf <- pcatdf

rdf$prev_price = log(rdf$prev_price)
rdf$prev_price[which(!is.finite(rdf$prev_price))] <- 0

rdf$month<- strftime(rdf$date,"%m")
rdf <- dummy_cols(rdf, select_columns = "month", remove_selected_columns=TRUE, remove_first_dummy=TRUE)
rdf = rdf[,!(names(rdf) %in% c("date"))]

rdf$rarityScore2 = rdf$rarityScore^2
colnames(rdf)
```

# Second regression

```{r}
reg2 = lm(log(price_in_usd) ~ . - first_transaction, data = rdf)
reg3 = lm(log(price_in_usd) ~ . - first_transaction, data = filter(rdf, first_transaction == 1))
reg4 = lm(log(price_in_usd) ~ . - first_transaction, data = filter(rdf, first_transaction == 0))

stargazer(reg1, reg2, reg3, reg4, title="Regression Results", align=TRUE, type="text")
```
