---
title: "Processing"
author: 'Team #3'
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warnign=FALSE}
setwd("~/Desktop/Thesis/code")
options(max.print=1000000)
library(readr)
library(stringr)
library(ggplot2)
library(dplyr)
library(corrplot)
library(gridExtra)
library(data.table)
library(fastDummies)
library(glmnet)
library(caret)
```

## Elastic Net
```{r}
rdf <- rtdf
set.seed(42) # Set seed for reproducibility

n <- dim(rdf)[1]    # Number of observations
p <- dim(rdf)[2]     # Number of predictors included in model

xdf <- select(rdf, -price_in_usd)
x <- data.matrix(xdf)
y <- log(rdf$price_in_usd)
#rownames(pcaMatrix) <- df$token_id

# Split data into train (2/3) and test (1/3) sets
train_rows <- sample(1:n, .66*n)
x.train <- x[train_rows, ]
x.test <- x[-train_rows, ]

y.train <- y[train_rows]
y.test <- y[-train_rows]

list.of.fits <- list()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)
  
  list.of.fits[[fit.name]] <-
    cv.glmnet(x.train, y.train, type.measure="mse", alpha=i/10, 
      family="gaussian")
}

results <- data.frame()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)
  
  predicted <- 
    predict(list.of.fits[[fit.name]], 
      s=list.of.fits[[fit.name]]$lambda.1se, newx=x.test)
  
  mse <- mean((y.test - predicted)^2)
  
  temp <- data.frame(alpha=i/10, mse=mse, fit.name=fit.name)
  results <- rbind(results, temp)
}

results
```

```{r}
reg1en <- cv.glmnet(x, y, type.measure="mse", alpha=0.5, family="gaussian")
coef(reg1en)
```



```{r}
rtdf <- select(df, price_in_usd, Close, date, rarityScore, winner_flow, winner_total_sold, winner_total_bought, prev_price, cur_increased, time_from_prev, whitelisted, whitelisted_count)
rtdf[is.na(rtdf)] <- 0
rtdf$prev_price = log(rtdf$prev_price)
rtdf$prev_price[which(!is.finite(rtdf$prev_price))] <- 0


rtdf$rarityScore = rtdf$rarityScore/1000
rtdf$rarityScore2 <- rtdf$rarityScore^2

rtdf$month<- strftime(rtdf$date,"%m")
rtdf <- dummy_cols(rtdf, select_columns = "month", remove_selected_columns=TRUE, remove_first_dummy=TRUE)
rtdf$weekday <- weekdays(as.Date(df$date))
rtdf <- dummy_cols(rtdf, select_columns = "weekday", remove_selected_columns=TRUE, remove_first_dummy=FALSE)

rtdf = rtdf[,!(names(rtdf) %in% c("date", "weekday_Monday"))]
colnames(rtdf)
```
