---
title: "Processing"
author: "Team #3"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r warnign=FALSE}
setwd("~/Desktop/Thesis/code")
options(max.print=1000000)
library(readr)
library(stringr)
library(ggplot2)
library(dplyr)
library(corrplot)
library(gridExtra)
library(data.table)
library(rattle)
library(fastDummies)
library(stargazer)
library(glmnet)
library(caret)
library(ISLR) #contains Hitters dataset
library(rpart) #for fitting decision trees
library(rpart.plot) #for plotting decision trees
library(randomForest)
library(neuralnet)
```

## Dataset preparation

```{r warnign=FALSE}
tdf <- read_csv("../data/MB_Traits_processed_continouse&sum.csv", show_col_types = FALSE)
tdf = tdf %>% filter(price_in_usd > 0)
tdf = tdf %>% filter(trait_Type != 7)
tdf[is.na(tdf)] <- 0
rating_tdf <- read_csv("./data/AllRating.csv", show_col_types = FALSE)
rarityScore_df <- read_csv("./data/RarityScore.csv", show_col_types = FALSE)

tdf <- merge(tdf, rarityScore_df, by = 'token_id')
tdf <- merge(tdf, rating_tdf, by = 'token_id')
```

# Choose variables

```{r}
# Rating, rarityScore,
rtdf <- select(tdf, rarityScore, trait_Type, trait_Pants, trait_Pants_Color, trait_Shoes, trait_Shoes_Color, trait_Shirt, trait_Shirt_Color, trait_Hair_Style, trait_Hair_Color, trait_Glasses, trait_Glasses_Color, trait_Overshirt, trait_Overshirt_Color, trait_Beard, trait_Beard_Color, trait_Hat, trait_Hat_Color, trait_Jersey_Number, trait_Necklace, trait_Earring)
rtdf[is.na(rtdf)] <- 0

colnms = colnames(rtdf)
c = 0
for (i in colnms) {
  if (c > 0) {
    print(i)
    rtdf <- dummy_cols(rtdf, select_columns = i, remove_selected_columns=TRUE, remove_first_dummy=FALSE)
  }
  c = c + 1
}

names(rtdf)[names(rtdf) == 'rarityScore'] <- "rating"

rtdf = rtdf[,!(names(rtdf) %in% c(
  "trait_Shoes_Color_0",
  "trait_Pants_Color_0",
  "trait_Pants_Color_19",
  "trait_Shirt_Color_0",
  "trait_Overshirt_Color_0",
  "trait_Hat_Color_0",
  "trait_Hair_Color_0",
  "trait_Beard_Color_0", # no beard without color
  "trait_Glasses_Color_0",
  "trait_Jersey_Number_0", # no Jersey stuff without number

  "trait_Necklace_0",
  "trait_Earring_0",

  "trait_Shirt_18", # Don't know why, but hoodie only exist without oveshirt

  "trait_Hat_Color_1",
  "trait_Beard_Color_1",
  "trait_Overshirt_Color_1",
  "trait_Glasses_Color_1",
  "trait_Hair_Color_1",
  "trait_Shirt_Color_1",
  "trait_Shoes_Color_1",

  "trait_Type_1",
  "trait_Shoes_1",
  "trait_Pants_1",
  "trait_Shirt_1",
  "trait_Overshirt_0",
  "trait_Hat_0",
  "trait_Hair_Style_1",
  "trait_Beard_0",
  "trait_Glasses_0",
  "trait_Jersey_Number_1"
  ))]

#colnames(rtdf)
```

## Devision

```{r}
rdf <- rtdf
set.seed(42) # Set seed for reproducibility

n <- dim(rdf)[1]    # Number of observations
p <- dim(rdf)[2]     # Number of predictors included in model

xdf <- select(rdf, -rating)
x <- data.matrix(xdf)
y <- log(rdf$rating)

# Split data into train (2/3) and test (1/3) sets
train_rows <- sample(1:n, .66*n)

train <- data.matrix(rdf)[train_rows, ]
test <- data.matrix(rdf)[-train_rows, ]

x.train <- x[train_rows, ]
x.test <- x[-train_rows, ]

y.train <- y[train_rows]
y.test <- y[-train_rows]
```

## Elastic Net

```{r}
list.of.fits <- list()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)

  list.of.fits[[fit.name]] <-
    cv.glmnet(x.train, y.train, type.measure="mse", alpha=i/10,
      family="gaussian")
}

results <- data.frame()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)

  predicted <-
    predict(list.of.fits[[fit.name]],
      s=list.of.fits[[fit.name]]$lambda.1se, newx=x.test)

  mse <- mean((y.test - predicted)^2)

  temp <- data.frame(alpha=i/10, mse=mse, fit.name=fit.name)
  results <- rbind(results, temp)
}

results
```

```{r}
reg <- cv.glmnet(x.train, y.train, type.measure="mse", alpha=0.6, family="gaussian")
#coef(reg)
bestlam = reg$lambda.min

ridge_pred = predict(reg, s = bestlam, newx = x.test)
sqrt(mean((ridge_pred - y.test)^2))
```

#RF

```{r}
rf <- randomForest(rating~., data=train, proximity=TRUE)

rf_pred <- predict(rf, x.test)
sqrt(mean((rf_pred - y.test)^2))
```

#NN

```{r}
nn <- neuralnet(rating~., data = train, hidden=c(208,10), threshold=0.01)

nn_pred <- compute(nn, x.test)
summary(nn_pred$net.result)
summary(y.test)

sqrt(mean((nn_pred$net.result - y.test)^2))
```
